drop table if exists cart_product CASCADE;
create table cart_product
(
    id        bigint generated by default as identity,
    cart_id integer,
    product_id integer,
    quantity integer,
    total_price integer,
    updated_time timestamp, --장바구니 내 상품의 수량이 변경된 날짜 및 시간

    FOREIGN KEY (cart_id) REFERENCES cart (id),
    FOREIGN KEY (product_id) REFERENCES product (id),

        primary key (id)
);
