drop table if exists cart CASCADE;
create table cart
(
    id        bigint generated by default as identity,
    user_id integer,
    update_time timestamp, --장바구니 내 상품의 수량이 변경된 날짜 및 시간

    primary key (id)
);
