drop table if exists cart_product CASCADE;
create table cart_product
(
    id        bigint generated by default as identity,
    cart_id integer,
    product_id integer,
    quantity integer,
    total_price integer,
    update_time timestamp, --장바구니 내 상품의 수량이 변경된 날짜 및 시간

    primary key (id)
);
