drop table if exists comment CASCADE;
create table comment
(
    id        bigint generated by default as identity,
    user_id integer,
    board_id integer,
    user_name varchar,
    content varchar,
    updated_time timestamp,
    page_number integer,
    like_count integer,


    primary key (id)
);
