drop table if exists product CASCADE;
create table product
(
    id        bigint generated by default as identity,
    name varchar,
    category varchar,
    image varchar,
    quantity   integer,
    price    integer,
    description varchar,
    read_count integer,
    like_count integer,
    update_time timestamp, --상품의 수량이 변경된 날짜 및 시간



    primary key (id)
);
